DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS BOOK_GENRE;

CREATE TABLE AUTHORS (ID LONG AUTO_INCREMENT PRIMARY KEY, SURNAME VARCHAR2(100), FIRSTNAME VARCHAR2(100), SECONDNAME VARCHAR2(100));
CREATE TABLE BOOKS (ID LONG AUTO_INCREMENT PRIMARY KEY, BOOKNAME VARCHAR2(200), NUMBERAVAILABLE INT);
CREATE TABLE GENRES (ID LONG AUTO_INCREMENT PRIMARY KEY, GENRENAME VARCHAR2(100));
CREATE TABLE BOOK_AUTHOR (ID LONG AUTO_INCREMENT PRIMARY KEY, AUTHORID LONG, BOOKID LONG);
CREATE TABLE BOOK_GENRE (ID LONG AUTO_INCREMENT PRIMARY KEY, BOOKID LONG, GENREID LONG);