INSERT INTO AUTHORS VALUES (1, 'Ильф', 'Илья', 'Арнольдович');
INSERT INTO AUTHORS VALUES (2, 'Петров', 'Евгений', 'Петрович');
INSERT INTO AUTHORS VALUES (3, 'Брэдбери', 'Рэй', '');
INSERT INTO AUTHORS VALUES (4, 'Донцова', 'Дарья', '');
INSERT INTO AUTHORS VALUES (5, 'Кастанеда', 'Карлос', '');
INSERT INTO AUTHORS VALUES (6, 'Гослинг', 'Джеймс', '');
INSERT INTO AUTHORS VALUES (7, 'Джой', 'Билл', '');
INSERT INTO AUTHORS VALUES (8, 'Стил', 'Гай', '');
INSERT INTO AUTHORS VALUES (9, 'Брача', 'Гилард', '');
INSERT INTO AUTHORS VALUES (10, 'Баксли', 'Алекс', '');

INSERT INTO BOOKS VALUES (1, 'Золотой теленок', 10);
INSERT INTO BOOKS VALUES (2, 'Двенадцать стульев', 8);
INSERT INTO BOOKS VALUES (3, 'О скитаньях вечных и о Земле', 2);
INSERT INTO BOOKS VALUES (4, 'Покер с акулой', 20);
INSERT INTO BOOKS VALUES (5, 'Язык программирования Java SE 8', 4);
INSERT INTO BOOKS VALUES (6, 'Учение дона Хуана: Путь знания индейцев — яки', 6);

INSERT INTO GENRES VALUES (1, 'Сатира');
INSERT INTO GENRES VALUES (2, 'Детектив');
INSERT INTO GENRES VALUES (3, 'Рассказы');
INSERT INTO GENRES VALUES (4, 'Фантастика');
INSERT INTO GENRES VALUES (5, 'Философский роман');
INSERT INTO GENRES VALUES (6, 'Эзотерика');
INSERT INTO GENRES VALUES (7, 'Компьютерная литература');

INSERT INTO BOOK_AUTHOR VALUES (1, 1,1);
INSERT INTO BOOK_AUTHOR VALUES (2, 2,1);
INSERT INTO BOOK_AUTHOR VALUES (3, 1,2);
INSERT INTO BOOK_AUTHOR VALUES (4, 2,2);
INSERT INTO BOOK_AUTHOR VALUES (5, 3,3);
INSERT INTO BOOK_AUTHOR VALUES (6, 4,4);
INSERT INTO BOOK_AUTHOR VALUES (7, 5,6);
INSERT INTO BOOK_AUTHOR VALUES (8, 6,5);
INSERT INTO BOOK_AUTHOR VALUES (9, 7,5);
INSERT INTO BOOK_AUTHOR VALUES (10, 8,5);
INSERT INTO BOOK_AUTHOR VALUES (11, 9,5);
INSERT INTO BOOK_AUTHOR VALUES (12, 10,5);

INSERT INTO BOOK_GENRE VALUES (1, 1,1);
INSERT INTO BOOK_GENRE VALUES (2, 2,1);
INSERT INTO BOOK_GENRE VALUES (3, 3,3);
INSERT INTO BOOK_GENRE VALUES (4, 3,4);
INSERT INTO BOOK_GENRE VALUES (5, 4,2);
INSERT INTO BOOK_GENRE VALUES (6, 5,7);
INSERT INTO BOOK_GENRE VALUES (7, 6,6);
INSERT INTO BOOK_GENRE VALUES (8, 6,5);
